### ISSUE TITLE
Awesome work! Waiting for the source codes!

### ISSUE THREAD

**Issue by SuperBruceJia** [zihuazheng/DIP#1]

**Comment by GuitarZH** [comment]
Thanks for your excellent work! When will you plan to release the codebase?

**Comment by zihuazheng** [comment]
> Thanks for your excellent work! When will you plan to release the codebase?

Sorry for the delay of the open source code due to the busy project. We have released the first version of the code and demo, hope to get your further feedback.

**Comment by hofingermarkus** [comment]
Cool work!
What license does your code have? BSD-3 like RAFT or something else?

**Comment by zihuazheng** [comment]
> 

Thanks for acknowledging our work. The license is BSD-3 like RAFT
