### ISSUE TITLE
Export model to ONNX (output mismatch)

### ISSUE THREAD

**Issue by PhNeu23** [zihuazheng/DIP#11]
I wanted to export the model (DIP_kitti.pth) to ONNX.
To achieve this, I followed the example for DIP_stereo, changed some things and added the init_flow. 
I was able to export the model, but realized that the output of the Pytorch and ONNX model are not sufficiently similar.  Unfortunately, I don't know what the reason for this could be.  I therefore wanted to ask you if you could also provide a file for exporting this model or give me tips on how to successfully convert this model (with only small mismatch)?

**Comment by zihuazheng** [comment]
> I wanted to export the model (DIP_kitti.pth) to ONNX. To achieve this, I followed the example for DIP_stereo, changed some things and added the init_flow. I was able to export the model, but realized that the output of the Pytorch and ONNX model are not sufficiently similar. Unfortunately, I don't know what the reason for this could be. I therefore wanted to ask you if you could also provide a file for exporting this model or give me tips on how to successfully convert this model (with only small mismatch)?

My sincere apologies for the delayed response due to the heavy workload on the current project. I hope the issue has been resolved. If not, I will allocate time to thoroughly investigate and address it as soon as possible
