### ISSUE TITLE
Question about correlation computation in inverse propagation

### ISSUE THREAD

**Issue by TientJan** [zihuazheng/DIP#5]
Hello~ thanks for your great work! I am reading your code and am confused by this line:
`self.view_map1 = fmap1.view(self.N, self.C//2, 2, 1, self.D, self.H, self.W)`
This is in the correlation computation part. Why the channel is devided by 2 and the fmap is viewed? Does this mean 2 different axises representing x and y?

**Comment by zihuazheng** [comment]
Inspired by the transformer's multi-head attention, we added this operation. It was also confirmed in CRE stereo（https://github.com/megvii-research/CREStereo） that this operation can increase the point to a certain extent.
