### ISSUE TITLE
On gpu, why onnx model cost more time than pytorch?

### ISSUE THREAD

**Issue by QsaiShenG** [zihuazheng/DIP#6]
I use onnxruntime api to run DIP model. I noticed that it cost 1272ms. pytorch model only cost 340ms. why? Isn't the ONNX model supposed to inference faster?

**Comment by zihuazheng** [comment]
> I use onnxruntime api to run DIP model. I noticed that it cost 1272ms. pytorch model only cost 340ms. why? Isn't the ONNX model supposed to inference faster?

This performance issue may be attributed to the "grid_sample" operator. When I eliminate this operation and employ a pre-computed tensor as the correlation output, during the 'warm-up' phase, the processing time for a 1024x768 resolution is consistently 100ms on both PyTorch and ONNX.

**Comment by zihuazheng** [comment]
When I replace 'grid_sample' with the operation of https://zenn.dev/pinto0309/scraps/7d4032067d0160, onnx can reach a speed of 150ms, but pytorch drops to 130ms

**Comment by QsaiShenG** [comment]
Thanks,I will try it

**Comment by QsaiShenG** [comment]
thanks again. I  use tensorrt to inference this model instead of onnxruntime. And tensorrt can reach a speed of near 100ms at the first time. onnxruntime cost more time maybe it use cpu to compute some operators .
