### ISSUE TITLE
What dataset used to train DIP_stereo.pth?

### ISSUE THREAD

**Issue by VictorQuan2023** [zihuazheng/DIP#7]
I want to use tensorrt to quantize DIP onnx model to int8. 
I inherit nvinfer1::IInt8EntropyCalibrator2. I need a dataset to do calibrate.And your pretrained model DIP_stereo.pth work well.
So what dataset you used to train DIP_stereo.pth?
Which datasets can i use it as calibration data?

**Comment by zihuazheng** [comment]
DIP_stereo is trained on data from flyingthings and CRE. The input is the rectified image paires and has nothing to do with the calibration data. Maybe you can refer to this repository (https://github.com/pcb9382/StereoAlgorithms) for code configuration.

**Comment by VictorQuan2023** [comment]
可能是我英文不太好没表达清楚。我说的不是双目校正。。。我看Tensorrt的官方文档，有提供一个PTQ的量化接口。官方的量化INT8的方法需要提供一个校准集。这个校准集好像是最好是训练数据集中有代表性的数据。

**Comment by zihuazheng** [comment]
这个是预训练模型。多个数据集混合训练的。量化的接口标定我理解主要是标定中间数据的minmax/scale/offset，你可以用自己部署的批量数据跑一下应该就能统计出来，不用太多，一百组应该就够了

**Comment by VictorQuan2023** [comment]
我试了用自己的100组数据做为校准数据集去量化模型，量化完成后得到的精度明显有下降。我对比了下视差图每个像素的值，我把对应位置的像素亮度值差3以上就算错误，计算出来有30%多的错误。
这是我的校准数据集少了吗？还是其他的原因？

**Comment by zihuazheng** [comment]
> 我试了用自己的100组数据做为校准数据集去量化模型，量化完成后得到的精度明显有下降。我对比了下视差图每个像素的值，我把对应位置的像素亮度值差3以上就算错误，计算出来有30%多的错误。 这是我的校准数据集少了吗？还是其他的原因？

视差值差3个像素占30%以上，可能的原因：
1. PQT本身带来的精度损失，这个可以通过QAT来获得缓解；
2. 可以试试增加校准数据集，但是预计不会有更大的提升；
3. 可以尝试最后一层迭代不做量化。
另，如果方便，可以提供PQT的代码，我们可以一起分析分析

获取真实场景的数据集，有：
1. 公开数据集：sanp(https://github.com/google-research-datasets/sanpo_dataset)
2. 自己采集然后用各种大模型跑出来当蒸馏的GT
3. 虚幻引擎渲染一些偏真实的场景

**Comment by VictorQuan2023** [comment]
感谢回复。PQT的算法是tensorrt的算法：https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#enable_int8_c  第7点。
我准备这几天尝试一下最后一层迭代不做量化试下效果。

**Comment by VictorQuan2023** [comment]
感谢回复。PQT的算法是tensorrt的算法：https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#enable_int8_c  第7点。
我准备这几天尝试一下最后一层迭代不做量化试下效果。

**Comment by VictorQuan2023** [comment]
我把模型最后的迭代保留原有的精度量化后，达到了我的预期效果。量化前与量化后的视差图超过3个亮度值的像素占比3.25%。12层迭代次数在RTX 3060 的设备下一次推理耗时50ms左右。感谢您近期提供的帮助。(≧∇≦)

**Comment by zihuazheng** [comment]
> 我把模型最后的迭代保留原有的精度量化后，达到了我的预期效果。量化前与量化后的视差图超过3个亮度值的像素占比3.25%。12层迭代次数在RTX 3060 的设备下一次推理耗时50ms左右。感谢您近期提供的帮助。(≧∇≦)

实际应用中，1/16可以多迭代几次，如8次。1/4可以少迭代几次，如4次，也能取得不错的效果。应该可以进一步提速

**Comment by VictorQuan2023** [comment]
训练的代码有开源吗？ 可以上传吗？
